# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.2.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.2.1\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Ded\differentiator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Ded\differentiator\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2020.2.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2020.2.1\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Ded\differentiator\cmake-build-debug\CMakeFiles D:\Ded\differentiator\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Ded\differentiator\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named differentiator

# Build rule for target.
differentiator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 differentiator
.PHONY : differentiator

# fast build rule for target.
differentiator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/build
.PHONY : differentiator/fast

differentiator/differentiator.obj: differentiator/differentiator.cpp.obj

.PHONY : differentiator/differentiator.obj

# target to build an object file
differentiator/differentiator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/differentiator/differentiator.cpp.obj
.PHONY : differentiator/differentiator.cpp.obj

differentiator/differentiator.i: differentiator/differentiator.cpp.i

.PHONY : differentiator/differentiator.i

# target to preprocess a source file
differentiator/differentiator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/differentiator/differentiator.cpp.i
.PHONY : differentiator/differentiator.cpp.i

differentiator/differentiator.s: differentiator/differentiator.cpp.s

.PHONY : differentiator/differentiator.s

# target to generate assembly for a file
differentiator/differentiator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/differentiator/differentiator.cpp.s
.PHONY : differentiator/differentiator.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/main.cpp.s
.PHONY : main.cpp.s

tree/tree.obj: tree/tree.cpp.obj

.PHONY : tree/tree.obj

# target to build an object file
tree/tree.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/tree/tree.cpp.obj
.PHONY : tree/tree.cpp.obj

tree/tree.i: tree/tree.cpp.i

.PHONY : tree/tree.i

# target to preprocess a source file
tree/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/tree/tree.cpp.i
.PHONY : tree/tree.cpp.i

tree/tree.s: tree/tree.cpp.s

.PHONY : tree/tree.s

# target to generate assembly for a file
tree/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\differentiator.dir\build.make CMakeFiles/differentiator.dir/tree/tree.cpp.s
.PHONY : tree/tree.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... differentiator
	@echo ... differentiator/differentiator.obj
	@echo ... differentiator/differentiator.i
	@echo ... differentiator/differentiator.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... tree/tree.obj
	@echo ... tree/tree.i
	@echo ... tree/tree.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

